### ISSUE TITLE
Ability to write the configuration in YAML

### ISSUE THREAD

**Issue by shiroyuki** [shiroyuki/gallium#1]
The user should be able to write the configuration in YAML. It should be a straight-forward conversion between JSON and YAML.

**Pros:**
- Improve readability most of the time.

**Cons:**
- The startup time will be slightly/insignificantly slower.
- **Optionally** requires **PyYAML** to work with YAML files.

For example, from

``` json
{
    "extensions": [
        "shiroyuki.gallium.ext.BaconHamExtension",
        "shiroyuki.gallium.ext.TomYamExtension",
    ],
    "imports": [
        "shiroyuki.cmd"
    ]
}
```

become

``` yaml
extensions:
  - shiroyuki.gallium.ext.BaconHamExtension
  - shiroyuki.gallium.ext.TomYamExtension
imports:
  - shiroyuki.cmd
```
